FROM php:8.4-cli-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-dev \
 && docker-php-ext-install pdo_pgsql

COPY composer.json composer.lock ./
RUN composer install --no-interaction

COPY . .

CMD ["php", "artisan", "test"]
