FROM php:8.4-cli-alpine

WORKDIR /app

RUN apk add --no-cache \
    git \
    unzip \
    postgresql-dev \
 && docker-php-ext-install pdo_pgsql

COPY composer.json composer.lock ./
RUN composer install

COPY . .

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
