FROM php:8.4-cli-alpine

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git unzip libpq-dev \
 && docker-php-ext-install pdo_pgsql

COPY composer.json composer.lock ./
RUN composer install --no-interaction --prefer-dist

COPY . .

CMD ["php", "artisan", "test"]
